# Generated by Django 4.2.16 on 2024-11-03 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=15, unique=True, verbose_name='Nombre de usuario')),
                ('nombre', models.CharField(max_length=15, verbose_name='Nombre')),
                ('apellidos', models.CharField(max_length=15, verbose_name='Apellidos')),
                ('carnet_identidad', models.IntegerField(max_length=11, unique=True, verbose_name='Carnet de identidad')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='fotos/', verbose_name='Foto de perfil')),
                ('activo', models.BooleanField(default=False, verbose_name='Estado del usuario')),
                ('usuario_admin', models.BooleanField(default=False, verbose_name='Usuario admin')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
