# Generated by Django 4.2.16 on 2024-11-03 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='carnet_identidad',
            field=models.IntegerField(unique=True, verbose_name='Carnet de identidad'),
        ),
    ]
