# Generated by Django 4.2.16 on 2024-11-03 07:09

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_usuario_carnet_identidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='jugada',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Llave primaria')),
                ('numero_uno', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(75)])),
                ('numero_dos', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(75)])),
                ('numero_tres', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(75)])),
                ('numero_cuatro', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(75)])),
                ('numero_cinco', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(75)])),
                ('numero_seis', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(25)])),
                ('fecha_jugada', models.DateField(auto_now_add=True, verbose_name='Fecha de la jugada')),
                ('jugada_activa', models.BooleanField(default=True, verbose_name='Jugada activa/no activa')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
