# Generated by Django 4.2.16 on 2024-11-03 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_jugada'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='privilegios',
            field=models.CharField(choices=[('Supremo', 'Supremo'), ('Administrador', 'Administrador'), ('Usuario', 'Usuario')], default='Usuario', verbose_name='Privilegios'),
        ),
    ]
