# Generated by Django 4.2.16 on 2024-11-03 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_usuario_privilegios'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='monto',
            field=models.IntegerField(default=0, verbose_name='Saldo disponible'),
        ),
    ]
