# Generated by Django 4.2.16 on 2024-11-05 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_usuario_monto'),
    ]

    operations = [
        migrations.CreateModel(
            name='premio_ganador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premio', models.IntegerField()),
            ],
        ),
    ]
