# Generated by Django 4.2.16 on 2024-11-13 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0010_alter_usuario_privilegios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='privilegios',
            field=models.CharField(choices=[('Supremo', 'Supremo'), ('Administrador', 'Administrador'), ('Usuario', 'Usuario')], default='Usuario', verbose_name='Privilegios'),
        ),
    ]
