# Generated by Django 4.2.16 on 2024-11-14 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0011_alter_usuario_privilegios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='carnet_identidad',
            field=models.DecimalField(decimal_places=0, max_digits=11, unique=True, verbose_name='Carnet de identidad'),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
