# Generated by Django 4.2.16 on 2024-11-14 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0014_alter_usuario_privilegios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='privilegios',
            field=models.CharField(default='Usuario', max_length=20, verbose_name='Privilegios'),
        ),
    ]
