# Generated by Django 4.2.16 on 2024-11-06 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casaapuestas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='monto',
            field=models.IntegerField(default=0, verbose_name='Monto'),
        ),
    ]
