# Generated by Django 4.2.16 on 2024-11-06 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casaapuestas', '0002_transaccion_monto'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='fecha',
            field=models.DateField(auto_now=True, verbose_name='Fecha'),
        ),
    ]
